---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: thanos-bucket
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  data:
  - secretKey: saName
    remoteRef:
      key: secrets/sa-metrics
      property: sa-name  
  - secretKey: saKey
    remoteRef:
      key: secrets/sa-metrics
      property: sa-key
  target:
    name: thanos-bucket
    template:
      data:
        object-store.yaml: |
          type: AZURE
          config:
            storage_account: "{{`{{ .saName | toString }}`}}"
            storage_account_key: "{{`{{ .saKey | toString }}`}}"
            container: "thanos"
            endpoint: ""
            max_retries: 3
---
#OBS This is removed since this secret store is already a part of the prometheus deployment
#IF you DO NOT have the secret store from the prometheus repo in the org then you will propably want the below one

# apiVersion: external-secrets.io/v1alpha1
# kind: SecretStore
# metadata:
#   name: vault-backend
# spec:
#   provider:
#     vault:
#       server: "http://vault.tooling.svc:8200"
#       path: "k8s"
#       version: "v2"
#       auth:
#         # Authenticate against Vault using a Kubernetes ServiceAccount
#         # token stored in a Secret.
#         # https://www.vaultproject.io/docs/auth/kubernetes
#         kubernetes:
#           # Path where the Kubernetes authentication backend is mounted in Vault
#           mountPath: "kubernetes"
#           # A required field containing the Vault Role to assume.
#           role: "k8s-secrets"