{{ if .Values.querytls.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.componentname" (list $ "query") }}-tls
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: query-tls
{{ with .Values.querytls.deploymentLabels }}{{ toYaml . | indent 4 }}{{ end }}
  {{- with .Values.querytls.deploymentAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.querytls.autoscaling.enabled  }}
  replicas: {{ .Values.querytls.replicaCount | default 1 }}
  {{- end }}
  {{- with  .Values.querytls.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thanos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: query-tls
{{ with .Values.querytls.deploymentMatchLabels }}{{ toYaml . | indent 6 }}{{ end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "thanos.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: query-tls
{{ with  .Values.querytls.labels }}{{ toYaml . | indent 8 }}{{ end }}
      {{- if or .Values.querytls.annotations .Values.querytls.metrics.annotations.enabled }}
      annotations:
      {{- end }}
      {{- with  .Values.querytls.annotations }}{{ toYaml . | nindent 8 }}{{- end }}
      {{- if .Values.querytls.metrics.annotations.enabled  }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.querytls.http.port }}"
      {{- end }}
    spec:
      containers:
      - name: thanos-query-tls
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.querytls.extraEnv }}
        env: {{ toYaml . | nindent 8 }}
        {{- end }}
        args:
        - "query"
        - "--log.level={{ .Values.querytls.logLevel }}"
        - "--log.format={{ .Values.querytls.logFormat }}"
        - "--grpc-address=0.0.0.0:{{ .Values.querytls.grpc.port }}"
        - "--http-address=0.0.0.0:{{ .Values.querytls.http.port }}"
        - "--grpc-client-tls-secure"
        {{- range .Values.querytls.replicaLabels }}
        - "--query.replica-label={{ . }}"
        {{- end }}
        {{- if .Values.querytls.autoDownsampling }}
        - "--query.auto-downsampling"
        {{- end }}
        {{- if .Values.querytls.webRoutePrefix }}
        - "--web.route-prefix={{ .Values.querytls.webRoutePrefix }}"
        {{- end }}
        {{- if .Values.querytls.webExternalPrefix }}
        - "--web.external-prefix={{ .Values.querytls.webExternalPrefix }}"
        {{- end }}
        {{- if .Values.querytls.webPrefixHeader }}
        - "--web.prefix-header={{ .Values.querytls.webPrefixHeader }}"
        {{- end }}
        {{- if .Values.querytls.storeDNSResolver }}
        - "--store.sd-dns-resolver={{ .Values.querytls.storeDNSResolver }}"
        {{- end }}
        {{- if .Values.querytls.storeDNSDiscovery }}
        - "--store=dnssrv+_grpc._tcp.{{ include "thanos.componentname" (list $ "store") }}-grpc.{{ .Release.Namespace }}.svc.cluster.local"
        {{- end  }}
        {{- if .Values.querytls.sidecarDNSDiscovery }}
        - "--store=dnssrv+_grpc._tcp.{{ include "thanos.componentname" (list $ "sidecar") }}-grpc.{{ .Release.Namespace }}.svc.cluster.local"
        {{- end  }}
        {{- if .Values.querytls.ruleDNSDiscovery }}
        - "--store=dnssrv+_grpc._tcp.{{ include "thanos.componentname" (list $ "rule") }}-grpc.{{ .Release.Namespace }}.svc.cluster.local"
        {{- end  }}
        {{- range .Values.querytls.stores }}
        - "--store={{ . }}"
        {{- end }}
        {{- range .Values.querytls.serviceDiscoveryFiles }}
        - "--store.sd-files={{ . }}"
        {{- end }}
        {{- range .Values.querytls.serviceDiscoveryFileConfigMaps }}
        - "--store.sd-files=/etc/query/{{ . }}/*.yaml"
        - "--store.sd-files=/etc/query/{{ . }}/*.yml"
        - "--store.sd-files=/etc/query/{{ . }}/*.json"
        {{- end }}
        {{- if .Values.querytls.serviceDiscoveryInterval }}
        - "--store.sd-interval={{ .Values.querytls.serviceDiscoveryInterval }}"
        {{- end }}
        {{- if .Values.querytls.extraArgs }}
        {{ toYaml .Values.querytls.extraArgs | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.querytls.http.port}}
        - name: grpc
          containerPort: {{ .Values.querytls.grpc.port }}
        resources:
          {{ toYaml .Values.querytls.resources | nindent 10 }}
        volumeMounts:
        {{- range .Values.querytls.serviceDiscoveryFileConfigMaps }}
        - mountPath: /etc/query/{{ . }}
          name: {{ . }}
        {{- end }}
        {{- if .Values.querytls.certSecretName }}
        - mountPath: /etc/certs
          name: {{ .Values.querytls.certSecretName }}
          readOnly: true
        {{- end }}
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http
        readinessProbe:
          httpGet:
            path: /-/ready
            port: http
      volumes:
      {{- range .Values.querytls.serviceDiscoveryFileConfigMaps }}
      - name: {{ . }}
        configMap:
          defaultMode: 420
          name: {{ . }}
      {{- end }}
      {{- if .Values.querytls.certSecretName }}
      - name: {{ .Values.querytls.certSecretName }}
        secret:
          defaultMode: 420
          secretName: {{ .Values.querytls.certSecretName }}
      {{- end }}
      {{- with .Values.querytls.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.querytls.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.querytls.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.querytls.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with  (include "thanos.querytls.serviceaccount" . ) }}
      serviceAccountName: "{{ . }}"
      {{- end }}
{{ end }}
